graph LR
SRU((swissbib SRU)) -->|request / <br>response| MARC("swissbib<br>MARC21 (XML)")

MARC -->|Import| OpenRefine2[Bereinigung, Transformation, Normalisierung<br>mit OpenRefine]

subgraph Datentransformation
OpenRefine2 -->|Export| swissbib("swissbib<br>TSV")
end

swissbib -->|Indexierung| Solr(Suchindex<br>Apache Solr)

subgraph Discovery-System
Solr --- TYPO3((Katalogoberfläche<br>TYPO3 + TYPO3-find))
TYPO3 --> user(":-)")
end
